# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_shared_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shared_lists',
            field=models.ManyToManyField(db_table='accounts_listuser_shared_lists', related_name='shared_with', to='lists.List'),
        ),
    ]
